### PR TITLE
[FIX] Cleanup code

### PR DESCRIPTION
**Pull request by im-kulikov**

### CODE REVIEW

**Comment by im-kulikov** [comment]
@tidwall any explain?

**Comment by tidwall** [comment]
Thanks but this PR does not address any issues.

**Comment by im-kulikov** [comment]
- `json` collides with imported package name...
- fix linter warnings

**Comment by tidwall** [comment]
I'm not seeing the conflicts or warnings. Which version of Go are you using?

**Comment by Slach** [comment]
;) @im-kulikov you can just paste here your gometalinter linter

**Comment by im-kulikov** [comment]
```
gjson.go:1124::warning: declaration of "ok" shadows declaration at gjson.go:1116 (vetshadow)
gjson.go:1267::warning: declaration of "res" shadows declaration at gjson.go:1265 (vetshadow)
```

gjson golang src github com tidwall gjson - gjson go gjson 2018-02-11 12-27-37
gjson golang src github com tidwall gjson - gjson go gjson 2018-02-11 12-28-33

**Comment by tidwall** [comment]
Thanks for the additional context. I’ll take a look at reproducing from my side

**Comment by im-kulikov** [comment]
@tidwall ok 😉

**Comment by tidwall** [comment]
BTW, do you know how I could raise these warnings without installing GoLand? 
Optimally from the command line?

**Comment by im-kulikov** [comment]
Mb
- https://github.com/alecthomas/gometalinter ?
- https://github.com/golang/lint
- go vet
?

**Comment by Slach** [comment]
@tidwall 
you can use following receipe
```
go get https://github.com/alecthomas/gometalinter
gometalinter --enable-gc github.com/tidwall/gjson
```

**Comment by im-kulikov** [comment]
Seems like this is more usable:

```
$ cd $GOPATH/src/github.com/tidwall/gjson/
$ gometalinter --enable-gc ./...
```

**Comment by tidwall** [comment]
Thanks. I'll goof around and let you know.

**Comment by im-kulikov** [comment]
Cool

**Pull request closed without merging**
