### PR TITLE
Update gjson.go

### PR DESCRIPTION
**Pull request by youzeliang**
if !DisableModifiers   is  always true

### CODE REVIEW

**Review by youzeliang — COMMENTED** [review]
the  "!DisableModifiers" is always true . So the line 1797 should be delete

**Comment by tidwall** [comment]
Hi. Thanks for your PR. 
This specific condition is required in order to disable modifiers on application basis.

For example:

```go
package main

import "github.com/tidwall/gjson"

func main() {
    gjson.DisableModifiers = true

    // now modifiers are disabled for the life of the application.

}
```

**Comment by youzeliang** [comment]
ok，I got it wrong

**Comment by tidwall** [comment]
No worries. I plan on deprecating that flag at some point in future. Just not right now.

**Review by faves4less — APPROVED** [review]

**Pull request closed without merging**
