### PR TITLE
Modify behavior of Array() on non-array result.

### LINKED ISSUE #10: Behavior of Array() on non-array field
Hi

I have a particular case where a field can be either an array of strings, or a string.
Naively I tried to use `Array()` on the result when the field is a simple string to see if it would return an array with a single element, but instead the returned array is empty.

So I tried another solution, using the `myfield.#` notation on a non-array field, and I expected it to be zero, but instead i get `null`.

Do you know how I should address this use-case ? Would it be possible to return an array with a single element when using `Array()` on a non-array field ?

William

### PR DESCRIPTION
**Pull request by wI2L**
Closes #10.

### CODE REVIEW

**Comment by wI2L** [comment]
@tidwall Just thought that I didn't update the README. Perhaps it could be usefull to add a note for the behavior of the `Array()` method.

**Comment by tidwall** [comment]
I made a small mention on the README about `Array()`. Also I noticed that calling Array() on a path that does not exist a single item array with a Null a null result. For example:

```go
gjson.Get(`{"item":null}`, "item1").Array()
gjson.Get(`{}`, "item").Array()
```

Both return []gjson.Result{null}. Though only the first one should return an array with one item.

I pushed an update to address this.

**Comment by wI2L** [comment]
Good catch & thanks for the amazin work on the library btw 😄

**Comment by tidwall** [comment]
You're welcome and thanks a ton for you help.

**Pull request merged**
