### PR TITLE
Fixed syntax document for escape character

### PR DESCRIPTION
**Pull request by Prithvipal**

### CODE REVIEW

**Comment by tidwall** [comment]
I feel that the documentation is currently correct because the syntax for escaping is technically a single slash followed by the character that needs to be escaped.

The two slashes are only needed if you hardcode a path into Go string that is delimited by  double-quotes.

**Comment by tidwall** [comment]
Perhaps we can add a small notice such as:

---

### Escape character

Special purpose characters, such as `.`, `*`, and `?` can be escaped with `\`. 

```go
fav\.movie             "Deer Hunter"
```

You'll also need to make sure that the `\` character is correctly escaped when hardcoding a path in source code.

```go
res := gjson.Get(json, "fav\\.movie")  // must escape the slash
res := gjson.Get(json, `fav\.movie`)   // no need to escape the slash 
```

**Comment by Prithvipal** [comment]
@tidwall 
I have addressed your review suggestion.

**Comment by tidwall** [comment]
Thanks!

**Pull request merged**
